### ISSUE TITLE
Autoplay not autoplaying with image target

### ISSUE THREAD

**Issue by Mickellg** [8thwall/web#229]
My image is detected and everything works well, but even though I have autoplay in the video tag it doesn't autoplay when image is detected. Is there a way to auto play when image target is detected?

**Comment by dattanchu** [comment]
You can check if the issue is with the autoplay set up or with image target event set up. First use that same video tag and put it on your page and make it visible/not visible using a button. Does the video autoplay when it is visible? If it does not then the issue is with your autoplay set up.

Also, don't forget that autoplay will not work on video without muted.

**Comment by Mickellg** [comment]
Thank you @dattanchu from what I'm seeing now is that the problem just happens on iphone/IOS and not on android.

**Comment by Mickellg** [comment]
I figured out that on IOS, there is a fix for IOS 17 where you have to have for microphone permissions as well or the sound sometimes plays in the call speaker and not the speakers on the bottom of the phone. Also autoplay doesn't work, at least on iphone, if the low power mode or battery saver mode is on.

**Comment by dattanchu** [comment]
I see. Thanks for circling back with a solution.
