### ISSUE TITLE
Videos does not work on iOS - Safari

### ISSUE THREAD

**Issue by wajdibr** [8thwall/web#96]
Hello,

First of all, thank you for 8th wall.
I have a project that displays video in AR mode without any image recognition.
The problem is that i managed to display mp4 videos and any type on android, but not an only video worked in iOS.
I tried different devices, different OS versions (even iOS 11 and 13), different videos formats, (mp4, mov, ogv ...) nothing works.
Here an example of what i'm doing :
`<video id="video" loop crossOrigin="anonymous" webkit-playsinline style="display:none">
        <source src="my_video.mp4"
                type='video/mp4'>
</video>`

I have no issues by images by the way (so the website is whitelisted and everything is great)
And i have no problem with CORS because the video is on my server,

I could send you a private message for the link to be tested by you, i really tried every solution and i have an agency subscription.

Any help is welcome,

**Comment by atomarch** [comment]
Hello @wajdibr , are you using 8th Wall with A-Frame, three.js, or another platform?  I'd suggest taking a look at the following examples, both use image targets to play a video:

https://github.com/8thwall/web/tree/master/examples/aframe/flyer

https://github.com/8thwall/web/tree/master/examples/threejs/flyer

Note: browsers require the `muted` flag in order to autoplay video.

**Comment by ArfaouiHamouda** [comment]
Thanks alot @atomarch  , am working on the same project with @wajdibr  , i am using threejs and this Demo did work on my Current project , Thanks alot .
